### ISSUE TITLE
Issue with tilelive modules and v6.0

### ISSUE THREAD

**Issue by flemmens** [mojodna/tessera#34]
I just installed the v0.6.0 and now my system crashes when rendering the tiles, everything was working smoothly with previous version 0.5.3.

I use several tilelive modules (tmstyle, merge, mapbox, etc..). I also re-installed all these modules but the issue is still there. Any idea ?

Here are the message log when I launch tessera:
GET / 304 9.447 ms - -
GET /leaflet/dist/leaflet.css 304 7.333 ms - -
GET /leaflet/dist/leaflet.js 304 6.746 ms - -
GET /zepto/zepto.min.js 304 7.964 ms - -
GET /js/l.control.geosearch.js 304 1.231 ms - -
GET /leaflet-hash/leaflet-hash.js 304 5.506 ms - -
GET /js/l.geosearch.provider.nominatim.js 304 2.791 ms - -
GET /css/l.geosearch.css 304 0.539 ms - -
GET /images/transparent.png 304 1.098 ms - -
GET /index.json 304 8.264 ms - -
GET /images/geosearch.png 304 0.526 ms - -
node: symbol lookup error: /usr/local/lib/node_modules/tilelive-vector/node_modules/mapnik/lib/binding/node-v14-linux-x64/mapnik.node: undefined symbol: _ZN6icu_5513UnicodeStringC1ERKS0_

**Comment by mojodna** [comment]
Have you switched Node versions? Which version of mapnik is installed in `/usr/local/lib/node_modules/tilelive-vector/node_modules/mapnik` (check the `package.json` in that directory)?

It looks like you're installing `tessera` et al globally (`npm install -g`); this is often the result of that. If you're able, create a dummy project and install everything locally to that. It's also helpful to include `mapnik` as a top-level dependency (rather than allowing it to be installed multiple times).

`npm uninstall -g tilelive-vector` may help the situation...

**Comment by flemmens** [comment]
The mapnik version is 3.4.12. I uninstall and reinstall all the modules, now it works again but I have some other issues like the message "Cannot accept empty buffer as protobuf" with tilelive-merge which I did not with the previous version. Thanks for you reply anyway.

**Comment by mojodna** [comment]
It sounds like you've uncovered a new bug (or run into some stricter behavior on the Mapnik end of things). I'll try to get a fix out for `tilelive-merge` later today.

**Comment by mojodna** [comment]
`tilelive-merge` fix included in `tilelive-merge@1.0.3`.
