### ISSUE TITLE
WFS server proxy ?

### ISSUE THREAD

**Issue by cyrilchapon** [mojodna/tessera#85]
Hey :)

Is there any know way to proxying a plain old WFS server with this ? Maybe with tilelive-http plugin ?

Basically, the WFS server returns FeatureCollection, accepts some bbox arguments so this shouldn't be hard, but I can't find any example.

Thank :)

**Comment by mojodna** [comment]
I don't think tessera is a good fit for that; it's intended to serve up tiled data. Initially, that meant images, but with the advent of vector tiles, it's also those.

It would probably work if you wanted to serve up tiled WFS FeatureCollection responses, but you'd need to write your own tilelive module (perhaps similar to tilelive-http) in order to make the WFS requests and massage the responses accordingly.
