### ISSUE TITLE
Tiles URL starts with "https,http,http://..."

### ISSUE THREAD

**Issue by stevage** [mojodna/tessera#89]
I'm getting a weird issue with a server hosted on Glitch where the tileJSON contains this:

`"tiles":["https,http,http://demo-tessera.glitch.me/lgas/{z}/{x}/{y}.pbf"`

Obviously that's not a usable tile endpoint, so Mapbox-GL-JS chokes on it.

I'm mystified why this is happening or what to do about it.

Any ideas?

**Comment by stevage** [comment]
Ok, so the issue seems to be that for some reason Glitch is setting the `x-forwarded-proto` header to this:

`https,http,http`

Whereas Tessera is assuming it will always be a single protocol. Annoyingly it [doesn't seem to be a standard](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto) so there's no way to say who's right.

**Comment by mojodna** [comment]
If I had to guess, the convention is probably to make them comma-delimited and append to the list, à la https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For#Syntax

I merged this for now, but it may make sense to attempt to split the list and shift the first element off, since that's what's seen by a client.

**Comment by stevage** [comment]
Oh, thanks - that makes sense. Not something I know much about.
