### ISSUE TITLE
symbol lookup error node.mapnik

### ISSUE THREAD

**Issue by ghost** [mojodna/tessera#9]
hi, appologies if this is the wrong place to ask this: I have an error which I can't figure out.

I installed tessera and started serving a tilemill 2 style. This worked great.

Then since the second time I tried starting tessera, it starts up, but when I load localhost:8080 in a browser it crashes with the following error, with the console output that comes before:

GET / 200 30ms - 1.9kb
GET /css/leaflet-0.7.2.css 200 36ms - 9.92kb
GET /css/l.geosearch.css 200 2ms - 1.16kb
GET /js/leaflet-hash.js 200 48ms - 3.38kb
GET /js/leaflet-0.7.2.js 200 48ms - 122.27kb
GET /js/zepto.min.js 200 51ms - 24.06kb
GET /js/l.control.geosearch.js 200 68ms - 5.11kb
GET /js/l.geosearch.provider.google.js 200 74ms - 1.59kb
GET /images/transparent.png 200 16ms - 951b
GET /index.json 200 5ms - 488b
GET /images/geosearch.png 200 84ms - 699b

node: symbol lookup error: /usr/local/lib/node_modules/tessera/node_modules/mapnik/lib/binding/mapnik.node: undefined symbol: _ZNK6icu_5313UnicodeString10doHashCodeEv

I've tried uninstalling and reinstalling various node modules, including forceful delete, but I don't know enough about nodejs to really know what I'm doing there. The only things I can remember doing since tessera was working:
- install PIL via apt-get
- install tilestache in a virtualenv
- modify the cartocss in the tilemill 2 project (though the crash happens with all styles)

My guess would be that I'm missing a dependency or have a wrong version or something, but I can't figure out what happened to break it.

Any ideas?

**Comment by georgbachmann** [comment]
Sorry guys... I have the same issue and tried to read this post several times but just don't get it.... 

What do I have to change in order to get tessera working? I have to manually uninstall a node-mapnik module? Problem is that I am not that familiar with node and therefor don't really know where that module would be. There is on mapnik folder in `/usr/local/lib/`But I guess deleting that one won't be correct, right?

Thanks, Georg

**Comment by mojodna** [comment]
Can you post the versions for:

* Node
* tessera

Did you install tessera globally?  Which other tile-related modules did you also install?

I've been installing tessera and dependencies locally (no `-g`) in order to get around this to whatever extent.  If I know there's going to be a conflict, I `npm install mapnik` first which prevents other modules that depend on it from installing their own versions.

**Comment by georgbachmann** [comment]
Thanks for your help!!!
I have those versions installed

    node  v0.10.29
    tessera v0.5.3

And yes, I did install tessera using the -g option (like it said in the readme). Installing it without `-g` makes it not being executable in the terminal :( but that might also be cause I don't really know much about node...

**Comment by mojodna** [comment]
Installing locally will put the binary in `./node_modules/.bin/tessera`, so running that should start it.

**Comment by georgbachmann** [comment]
hm... staring tessera like so will produce the following:

    ./tessera tmstyle:///home/osm-map/Documents/MapBoxData/osmMap.tm2/
    Listening at http://0.0.0.0:8080/
    
    /node_modules/tessera/server.js:43
        throw err;
              ^
Error: Invalid tilesource protocol: tmstyle:

**Comment by mojodna** [comment]
`npm install tilelive-tmstyle` (and whatever other deps are needed for your map) should help.

**Comment by georgbachmann** [comment]
my error is still there after `npm install tilelive-tmstyle`

**Comment by mojodna** [comment]
Still `Error: Invalid tilesource protocol: tmstyle:`?  Or is it complaining about a different protocol?

What's in the local `node_modules/` directory?

**Comment by georgbachmann** [comment]
I managed to get it working with a friend. We just removed the additional mapnik_node modules and it worked.... thanks!!!

**Comment by mojodna** [comment]
Great!

**Comment by arverma007** [comment]
> mapnik_node

How did you remove mapnik_node modules? pls reply
